image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: prod

stages:
  - build
  - package
  # - deploy
  # - int-test

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  script:
    - docker build -t registry.gitlab.com/vincent_lalere/woodblocktoys .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/vincent_lalere/woodblocktoys

#ssh-deploy:
#  image: kroniak/ssh-client
#  stage: deploy
#  script:
#    - echo "$SSH_KEY" > gcloud-test
#    - chmod 400 gcloud-test
#    - ssh -o StrictHostKeyChecking=no -i gcloud-test ubuntu@35.246.47.186 -C "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com"
#    - scp -o StrictHostKeyChecking=no -i gcloud-test docker/docker-compose.yml ubuntu@35.246.47.186:/home/ubuntu
#    - ssh -o StrictHostKeyChecking=no -i gcloud-test ubuntu@35.246.47.186 -C "docker-compose up -d"

#test-integration:
#  image: kroniak/ssh-client
#  stage: int-test
#  script:
#    - echo "$SSH_KEY" > gcloud-test
#    - chmod 400 gcloud-test
#    - "ssh -o StrictHostKeyChecking=no -i gcloud-test ubuntu@35.246.47.186 -C \"curl -X GET http://localhost:8080/cards -H 'Content-Type: application/json'\""